# Generated by Django 3.1.2 on 2020-10-19 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros_classificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
                ('observacao', models.TextField(max_length=1000)),
                ('data_cadastro', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('assinantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('destinacao_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.destinacaofinal')),
                ('fase_intermediaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.faseintermediaria')),
                ('frequencia_Uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.frequenciauso')),
                ('grau_sigio_documentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.grausigiodocumentacao')),
                ('prazos_guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.prazosguarda')),
                ('tipo_digitalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.tipodigitalizacao')),
            ],
        ),
    ]
