# Generated by Django 3.1.2 on 2020-10-20 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros_classificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
                ('observacao', models.TextField(max_length=1000)),
                ('data_cadastro', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinado', models.BooleanField()),
                ('data', models.DateField()),
                ('fk_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fk_usuario', 'fk_documento')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='assinantes',
            field=models.ManyToManyField(through='documento.DocumentoUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='destinacao_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.destinacaofinal'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fase_intermediaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.faseintermediaria'),
        ),
        migrations.AddField(
            model_name='documento',
            name='frequencia_Uso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.frequenciauso'),
        ),
        migrations.AddField(
            model_name='documento',
            name='grau_sigio_documentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.grausigiodocumentacao'),
        ),
        migrations.AddField(
            model_name='documento',
            name='prazos_guarda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.prazosguarda'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_digitalizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_classificacao.tipodigitalizacao'),
        ),
    ]
