# Generated by Django 3.1.2 on 2020-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
