# Generated by Django 3.1.2 on 2020-10-20 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinado', models.BooleanField()),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='assinantes',
        ),
        migrations.DeleteModel(
            name='DocumentoUsuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='assinaturas',
            field=models.ManyToManyField(to='documento.Assinatura'),
        ),
    ]
