# Generated by Django 3.1.2 on 2020-10-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_auto_20201020_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='assinado',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sent'), (2, 'paid'), (3, 'ASSINADO')], default=1),
        ),
    ]
