# Generated by Django 3.1.2 on 2020-10-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_documento_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='file',
            new_name='arquivo',
        ),
    ]
