# Generated by Django 3.1.2 on 2020-10-19 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento', '0003_auto_20201016_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='assinantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
